index:
   path: /
   controller: App\Controller\TestController::index


test: 
    path: /test/{age<\d+>?0}/{prenom<[a-zA-Z]+>?Nobody}
    controller: App\Controller\TestController::test
    # defaults:
    #   age: 0
    #   prenom: 'Nobody'
    # requirements: 
    #   age: \d+
    #   prenom: [a-zA-Z]+